name: Dependabot Auto-Merge

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions: {}

jobs:
  auto-merge:
    permissions:
      contents: write
      pull-requests: write
    uses: TaxSystems/shared-workflows/.github/workflows/dependabot-auto-merge.yml@master
    secrets: inherit
