name: NPM Package

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    uses: TaxSystems/shared-workflows/.github/workflows/npm-package.yml@master
    with:
      node-version: '22.x'
