name: Terraform Remote Backend

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  terraform:
    uses: TaxSystems/shared-workflows/.github/workflows/terraform-remote.yml@master
    with:
      tf-cloud-organization: ${{ vars.TF_CLOUD_ORGANIZATION }}
      tf-workspace: ${{ vars.TF_WORKSPACE }}
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
