name: Terraform Azure Backend

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  terraform:
    uses: TaxSystems/shared-workflows/.github/workflows/terraform-azure.yml@master
    with:
      tf-state-resource-group: ${{ vars.TF_STATE_RESOURCE_GROUP }}
      tf-state-storage-account: ${{ vars.TF_STATE_STORAGE_ACCOUNT }}
      tf-state-container: ${{ vars.TF_STATE_CONTAINER }}
      tf-state-key: ${{ vars.TF_STATE_KEY }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
